language: node_js

node_js:
    - stable
    - lts/*
    - 8
    - 6

install:
    - npm install

script:
    - npm run lint
    - npm run cover

after_script:
    - "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"

notifications:
    webhooks: https://www.travisbuddy.com/
