language: node_js

node_js:
    - stable
    - lts/*
    - 7
    - 6
    - 5

install:
    - npm install

script:
    - npm run lint
    - npm run cover

before_install: npm install -g greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update

after_script:
    - "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
    - greenkeeper-lockfile-upload

after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
