language: node_js

node_js:
    - stable
    - 7
    - 6
    - 5

install:
    - yarn

script:
    - yarn lint
    - yarn cover

after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"

after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
